!jira tips command
mojira/mojira-discord-bot pull request #128
Opened 2020-11-20 22:32 UTC by chandler05

## Purpose
Close #113
## Future work
The wording of the tips message could definitely be changed, feedback on it is probably needed

2020-11-21 00:07 UTC, dericksonmark requested changes
I've never reviewed anything before but here is one. I don't know if I needed to write the line numbers in my comments, so I did it anyway. Sorry if I did anything wrong!

2020-11-21 00:16 UTC, chandler05 commented on src/commands/TipsCommand.ts
> +				Afterwards, you can use correspondidng request channels in each project to make requests for things on the bug tracker, like resolutions and adding affected versions.
Thanks for the feedback :)

2020-11-21 00:17 UTC, dericksonmark commented on src/commands/TipsCommand.ts
> +				Afterwards, you can use correspondidng request channels in each project to make requests for things on the bug tracker, like resolutions and adding affected versions.
Thank you for making the changes :)

2020-11-21 00:34 UTC, dericksonmark approved these changes

2020-12-05 02:47 UTC, SPGoding approved these changes

2020-12-05 02:47 UTC, SPGoding commented on src/commands/TipsCommand.ts
> +import BotConfig from '../BotConfig';
```
GitHub Actions / build (12.x)

src/commands/TipsCommand.ts#L3

'BotConfig' is defined but never used
```

2020-12-05 02:47 UTC, SPGoding commented on src/commands/TipsCommand.ts
> +				For help using the bug tracker, there is an article on the Minecraft website that you can read: https://help.minecraft.net/hc/articles/360049840492
```suggestion
				For help with using the bug tracker, there is an article on the Minecraft website that you can read: <https://help.minecraft.net/hc/articles/360049840492>.
```

2020-12-05 02:47 UTC, SPGoding commented on src/commands/TipsCommand.ts
> +				The mods and helpers of the bug tracker will then be able to see the requests and resolve them.`.replace( /\t/g, '' )
```suggestion
				The moderators and helpers of the bug tracker will then be able to see the requests and resolve them.`.replace( /\t/g, '' )
```

2020-12-06 21:57 UTC, merged